- name: Deploy to Kubernetes
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Login (OpenShift case)
      shell: |
        oc login https://api.cluster:6443 \
        --token={{ lookup('env','TOKEN') }} \
        --insecure-skip-tls-verify=true

    - name: Apply deployment
      shell: kubectl apply -f {{ playbook_dir }}/../deployment.yaml --validate=false

    - name: Apply service
      shell: kubectl apply -f {{ playbook_dir }}/../service.yaml --validate=false
